//! `PythonGenerator` — generates an importable Python module.
//!
//! Each upstream tool becomes a synchronous function that calls `POST /exec`
//! on the local tool proxy.  The generated module:
//!
//! - Is named `<cli_name>.py`.
//! - Uses only the standard library (`urllib`) for HTTP calls.
//! - Contains `_BRIDGE` and `_TOKEN` module-level constants.
//! - Has one `def <tool_name>(...)` function per upstream tool with:
//!   - Required params first; optional params default to `None` (omitted on the wire).
//!   - Type annotations derived from each property's JSON Schema type.
//!   - A docstring with the tool's description and an `Args:` section.
//!   - Return type annotation of `str`.
//! - Contains a `# generated by mcp-compressor — do not edit manually` header.

use crate::client_gen::generator::{
    bind_params, safe_identifier, string_literal, ClientGenerator, GeneratedArtifact,
    GeneratorConfig, ParamBinding,
};
use crate::Error;

pub struct PythonGenerator;

impl ClientGenerator for PythonGenerator {
    fn render(&self, config: &GeneratorConfig) -> Result<Vec<GeneratedArtifact>, Error> {
        Ok(vec![GeneratedArtifact::new(
            format!("{}.py", config.cli_name),
            render_python_module(config),
        )])
    }
}

fn render_python_module(config: &GeneratorConfig) -> String {
    let mut module = format!(
        r#"# generated by mcp-compressor — do not edit manually
from __future__ import annotations

import json as _json
import urllib.error as _urllib_error
import urllib.request as _urllib_request

_BRIDGE = {bridge:?}
_TOKEN = {token:?}
_SESSION_PID = {pid}
_HEADERS = {{"Content-Type": "application/json", "Authorization": f"Bearer {{_TOKEN}}"}}




def _unwrap_proxy_response(body: str) -> str:
    try:
        parsed = _json.loads(body)
    except Exception:
        return body
    if isinstance(parsed, dict) and set(parsed.keys()) == {{"result"}}:
        result = parsed["result"]
        return result if isinstance(result, str) else _json.dumps(result, separators=(",", ":"))
    return body


def _exec(tool: str, tool_input: dict) -> str:
    # Omitted optional arguments are None; leave them out like the CLI and TS clients do.
    tool_input = {{key: value for key, value in tool_input.items() if value is not None}}
    payload = _json.dumps({{"tool": tool, "input": tool_input}}).encode()
    request = _urllib_request.Request(_BRIDGE + "/exec", data=payload, headers=_HEADERS, method="POST")
    try:
        with _urllib_request.urlopen(request) as response:
            return _unwrap_proxy_response(response.read().decode())
    except _urllib_error.HTTPError as exc:
        body = exc.read().decode(errors="replace")
        try:
            parsed = _json.loads(body)
        except Exception:
            parsed = None
        if isinstance(parsed, dict) and isinstance(parsed.get("error"), str):
            raise RuntimeError(parsed["error"]) from None
        raise RuntimeError(
            f"mcp-compressor proxy returned HTTP {{exc.code}}: {{body or exc.reason}}"
        ) from None
    except OSError as exc:
        details = getattr(exc, "reason", exc)
        raise RuntimeError(
            "mcp-compressor proxy is not running; restart the mcp-compressor process and try again. "
            f"details: {{details}}"
        ) from None
"#,
        bridge = config.bridge_url,
        token = config.token,
        pid = config.session_pid,
    );

    for tool in &config.tools {
        let bindings = bind_params(ordered_param_names(tool), python_identifier);
        module.push_str(&format!(
            r#"

def {name}({params}) -> str:
    """{docstring}"""
    return _exec({tool_name}, {input})
"#,
            name = python_identifier(&tool.name),
            params = python_params(&bindings, tool),
            docstring = python_docstring(tool, &bindings),
            tool_name = string_literal(&tool.name),
            input = python_input_dict(&bindings, tool),
        ));
    }

    module
}

/// Python hard keywords, plus the module-level names the generated client defines.
const PYTHON_RESERVED: &[&str] = &[
    "False",
    "None",
    "True",
    "and",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "class",
    "continue",
    "def",
    "del",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "from",
    "global",
    "if",
    "import",
    "in",
    "is",
    "lambda",
    "nonlocal",
    "not",
    "or",
    "pass",
    "raise",
    "return",
    "try",
    "while",
    "with",
    "yield",
    "_json",
    "_urllib_error",
    "_urllib_request",
    "_BRIDGE",
    "_TOKEN",
    "_SESSION_PID",
    "_HEADERS",
    "_unwrap_proxy_response",
    "_exec",
];

fn python_identifier(name: &str) -> String {
    safe_identifier(name, to_snake_case, PYTHON_RESERVED)
}

/// Escape a tool description for use inside a `"""` docstring.
///
/// Backslashes are doubled so sequences such as `\N` or `\u` in regexes and
/// Windows paths are not parsed as escapes, and every `"` is escaped so the
/// text can neither close the docstring early nor run into its closing quotes.
fn python_docstring_body(description: &str) -> String {
    description.replace('\\', "\\\\").replace('"', "\\\"")
}

fn python_params(bindings: &[ParamBinding], tool: &crate::compression::engine::Tool) -> String {
    bindings
        .iter()
        .map(|binding| {
            let hint = python_type(property_schema(tool, &binding.wire_name));
            match (binding.required, hint) {
                (true, Some(hint)) => format!("{}: {hint}", binding.identifier),
                (true, None) => binding.identifier.clone(),
                (false, Some(hint)) => format!("{}: {hint} | None = None", binding.identifier),
                (false, None) => format!("{}=None", binding.identifier),
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn property_schema<'a>(
    tool: &'a crate::compression::engine::Tool,
    name: &str,
) -> Option<&'a serde_json::Value> {
    tool.input_schema.get("properties")?.get(name)
}

/// A builtin annotation for a property, or `None` when the schema has no
/// single clear type. The module uses `from __future__ import annotations`,
/// so `int | None` is fine on any Python 3 version.
fn python_type(schema: Option<&serde_json::Value>) -> Option<&'static str> {
    use serde_json::Value;
    let schema = schema?.as_object()?;
    let ty = match schema.get("type")? {
        Value::String(ty) => ty.as_str(),
        // `["string", "null"]` is still a string; the param defaults to None.
        Value::Array(types) => {
            let mut non_null = types
                .iter()
                .filter_map(Value::as_str)
                .filter(|t| *t != "null");
            let ty = non_null.next()?;
            if non_null.next().is_some() {
                return None;
            }
            ty
        }
        _ => return None,
    };
    Some(match ty {
        "string" => "str",
        "integer" => "int",
        "number" => "float",
        "boolean" => "bool",
        "array" => "list",
        "object" => "dict",
        _ => return None,
    })
}

/// Docstring body: the tool description, then a Google-style `Args:` section
/// for documented parameters (including their allowed values, if any).
fn python_docstring(tool: &crate::compression::engine::Tool, bindings: &[ParamBinding]) -> String {
    let mut text = tool.description.as_deref().unwrap_or("").trim().to_string();
    let args: Vec<String> = bindings
        .iter()
        .filter_map(|binding| {
            let schema = property_schema(tool, &binding.wire_name)?;
            let mut description = schema
                .get("description")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("")
                .split_whitespace()
                .collect::<Vec<_>>()
                .join(" ");
            if let Some(values) = schema.get("enum").and_then(serde_json::Value::as_array) {
                let values = values
                    .iter()
                    .map(|value| {
                        value
                            .as_str()
                            .map_or_else(|| value.to_string(), str::to_string)
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                if !description.is_empty() {
                    description.push(' ');
                }
                description.push_str(&format!("One of: {values}."));
            }
            (!description.is_empty())
                .then(|| format!("        {}: {description}", binding.identifier))
        })
        .collect();
    if !args.is_empty() {
        if !text.is_empty() {
            text.push_str("\n\n");
        }
        text.push_str("    Args:\n");
        text.push_str(&args.join("\n"));
        text.push_str("\n    ");
    }
    python_docstring_body(&text)
}

/// Render the payload object, keeping the schema's property order on the wire.
fn python_input_dict(bindings: &[ParamBinding], tool: &crate::compression::engine::Tool) -> String {
    let schema_order = tool.param_names();
    let mut ordered: Vec<&ParamBinding> = bindings.iter().collect();
    ordered.sort_by_key(|binding| {
        schema_order
            .iter()
            .position(|name| *name == binding.wire_name)
    });
    let pairs = ordered
        .iter()
        .map(|binding| {
            format!(
                "{}: {}",
                string_literal(&binding.wire_name),
                binding.identifier
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("{{{pairs}}}")
}

fn to_snake_case(name: &str) -> String {
    let mut output = String::new();
    let mut previous_was_separator = false;
    for (index, ch) in name.chars().enumerate() {
        if ch == '-' || ch == ' ' {
            if !output.is_empty() && !previous_was_separator {
                output.push('_');
            }
            previous_was_separator = true;
        } else if ch.is_ascii_uppercase() {
            if index > 0 && !previous_was_separator {
                output.push('_');
            }
            output.push(ch.to_ascii_lowercase());
            previous_was_separator = false;
        } else {
            output.push(ch);
            previous_was_separator = ch == '_';
        }
    }
    output
}

fn ordered_param_names(tool: &crate::compression::engine::Tool) -> Vec<(String, bool)> {
    let required = required_params(tool);
    let mut params = tool
        .param_names()
        .into_iter()
        .map(|name| {
            let is_required = required.contains(&name);
            (name, is_required)
        })
        .collect::<Vec<_>>();
    params.sort_by_key(|(_name, is_required)| !*is_required);
    params
}

fn required_params(tool: &crate::compression::engine::Tool) -> Vec<String> {
    tool.input_schema
        .get("required")
        .and_then(serde_json::Value::as_array)
        .map(|values| {
            values
                .iter()
                .filter_map(serde_json::Value::as_str)
                .map(ToString::to_string)
                .collect()
        })
        .unwrap_or_default()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::client_gen::generator::test_helpers::{make_config, make_config_multiword_tool};
    use crate::client_gen::{ClientGenerator, GeneratorConfig};
    use crate::compression::engine::Tool;
    use std::ffi::OsStr;
    use std::fs;

    // ------------------------------------------------------------------
    // File creation
    // ------------------------------------------------------------------

    /// generate() returns exactly one path (the .py module).
    #[test]
    fn generate_returns_one_file() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        assert_eq!(paths.len(), 1, "expected exactly one generated file");
    }

    /// The generated file has a `.py` extension.
    #[test]
    fn generated_file_has_py_extension() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        assert_eq!(
            paths[0].extension(),
            Some(OsStr::new("py")),
            "expected .py extension",
        );
    }

    /// The generated file is named `<cli_name>.py`.
    #[test]
    fn generated_file_named_after_cli_name() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        assert_eq!(paths[0].file_name(), Some(OsStr::new("my-server.py")));
    }

    /// The generated file exists on disk.
    #[test]
    fn generated_file_exists() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        assert!(paths[0].exists());
    }

    // ------------------------------------------------------------------
    // File content — header
    // ------------------------------------------------------------------

    /// The file starts with the "do not edit manually" comment.
    #[test]
    fn file_has_do_not_edit_header() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        assert!(
            content.contains("do not edit"),
            "expected 'do not edit' header, got: {content:?}",
        );
    }

    // ------------------------------------------------------------------
    // File content — constants
    // ------------------------------------------------------------------

    /// The file contains `_TOKEN` with the session token value.
    #[test]
    fn file_contains_token_constant() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        assert!(content.contains(&config.token), "token not found in file");
        assert!(content.contains("_TOKEN"), "_TOKEN constant not found");
    }

    /// The file contains `_BRIDGE` with the proxy URL.
    #[test]
    fn file_contains_bridge_constant() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        assert!(
            content.contains(&config.bridge_url),
            "bridge URL not found in file"
        );
        assert!(content.contains("_BRIDGE"), "_BRIDGE constant not found");
    }

    // ------------------------------------------------------------------
    // File content — function definitions
    // ------------------------------------------------------------------

    /// Each upstream tool produces a `def <name>(...)` function.
    #[test]
    fn file_contains_function_per_tool() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        assert!(content.contains("def fetch("), "'def fetch(' not found");
        assert!(content.contains("def search("), "'def search(' not found");
    }

    /// Each function contains a docstring derived from the tool's description.
    #[test]
    fn function_has_docstring_from_description() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        assert!(
            content.contains("Fetch a URL"),
            "tool description not found in docstring"
        );
        assert!(
            content.contains("Search the web"),
            "tool description not found in docstring"
        );
    }

    /// Function parameters match the tool's schema properties.
    #[test]
    fn function_params_match_schema() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        // fetch() has "url" param; search() has "query" param
        assert!(content.contains("url"), "'url' param not found");
        assert!(content.contains("query"), "'query' param not found");
    }

    /// Functions have a `-> str` return type annotation.
    #[test]
    fn function_has_str_return_annotation() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        assert!(
            content.contains("-> str"),
            "-> str return annotation not found"
        );
    }

    /// Required params appear without a default value; optional params use `None`.
    #[test]
    fn required_params_have_no_default_optional_have_none() {
        let dir = tempfile::tempdir().unwrap();
        // make_config has "url" as required for fetch, no optional
        let config = make_config(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        // "url" is required → no "= None" for url
        // (this test verifies the function signature handles optionality)
        assert!(
            content.contains("url"),
            "'url' param not found in generated file"
        );
    }

    #[test]
    fn required_params_are_ordered_before_optional_params() {
        let dir = tempfile::tempdir().unwrap();
        let config = GeneratorConfig {
            cli_name: "real".to_string(),
            bridge_url: "http://127.0.0.1:1".to_string(),
            token: "token".to_string(),
            tools: vec![Tool::new(
                "real_tool",
                Some("Real schema".to_string()),
                serde_json::json!({
                    "type": "object",
                    "properties": {
                        "optional_first": {"type": "string"},
                        "required_second": {"type": "string"},
                        "optional_third": {"type": "string"}
                    },
                    "required": ["required_second"]
                }),
            )],
            session_pid: 1,
            output_dir: dir.path().to_path_buf(),
            extra_cli_bridges: Vec::new(),
        };
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        assert!(content.contains(
            "def real_tool(required_second: str, optional_first: str | None = None, optional_third: str | None = None) -> str:"
        ));
        assert!(content.contains("{\"optional_first\": optional_first, \"required_second\": required_second, \"optional_third\": optional_third}"));
        let python = std::env::var("PYTHON").unwrap_or_else(|_| "python3".to_string());
        std::process::Command::new(&python)
            .arg("-m")
            .arg("py_compile")
            .arg(&paths[0])
            .status()
            .expect("python should run")
            .success()
            .then_some(())
            .expect("generated Python should compile");
    }

    #[test]
    fn camel_case_tool_and_params_are_pythonic_snake_case_but_payload_keeps_original_keys() {
        let dir = tempfile::tempdir().unwrap();
        let config = GeneratorConfig {
            cli_name: "atlassian".to_string(),
            bridge_url: "http://127.0.0.1:1".to_string(),
            token: "token".to_string(),
            tools: vec![Tool::new(
                "searchJiraIssuesUsingJql",
                Some("Search issues with JQL".to_string()),
                serde_json::json!({
                    "type": "object",
                    "properties": {
                        "cloudId": {"type": "string"},
                        "maxResults": {"type": "number"},
                        "nextPageToken": {"type": "string"}
                    },
                    "required": ["cloudId"]
                }),
            )],
            session_pid: 1,
            output_dir: dir.path().to_path_buf(),
            extra_cli_bridges: Vec::new(),
        };
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        assert!(content.contains("def search_jira_issues_using_jql(cloud_id: str, max_results: float | None = None, next_page_token: str | None = None) -> str:"));
        assert!(content.contains(
            r#"{"cloudId": cloud_id, "maxResults": max_results, "nextPageToken": next_page_token}"#
        ));
        let python = std::env::var("PYTHON").unwrap_or_else(|_| "python3".to_string());
        std::process::Command::new(&python)
            .arg("-m")
            .arg("py_compile")
            .arg(&paths[0])
            .status()
            .expect("python should run")
            .success()
            .then_some(())
            .expect("generated Python should compile");
    }

    // ------------------------------------------------------------------
    // Multi-word tool names
    // ------------------------------------------------------------------

    /// A multi-word tool uses its original snake_case name as the function name.
    #[test]
    fn multiword_tool_function_name_is_snake_case() {
        let dir = tempfile::tempdir().unwrap();
        let config = make_config_multiword_tool(dir.path());
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        // Python keeps snake_case for function names
        assert!(
            content.contains("def get_confluence_page("),
            "expected snake_case function name, got: {content:?}",
        );
    }

    #[test]
    fn signatures_have_type_hints_and_args_docstring() {
        let dir = tempfile::TempDir::new().unwrap();
        let config = GeneratorConfig {
            cli_name: "typed".to_string(),
            bridge_url: "http://127.0.0.1:1".to_string(),
            token: "token".to_string(),
            tools: vec![Tool::new(
                "search_issues",
                Some("Search issues.".to_string()),
                serde_json::json!({
                    "type": "object",
                    "properties": {
                        "query": {"type": "string", "description": "JQL\n  query \"text\"."},
                        "limit": {"type": "integer"},
                        "order": {"type": "string", "enum": ["asc", "desc"]},
                        "tags": {"type": "array", "items": {"type": "string"}},
                        "filters": {"type": "object"},
                        "flag": {"type": ["boolean", "null"]},
                        "either": {"type": ["string", "integer"]},
                        "anything": {}
                    },
                    "required": ["query"]
                }),
            )],
            session_pid: 1,
            output_dir: dir.path().to_path_buf(),
            extra_cli_bridges: Vec::new(),
        };
        let paths = PythonGenerator.generate(&config).unwrap();
        let content = fs::read_to_string(&paths[0]).unwrap();
        assert!(
            content.contains(
                "def search_issues(query: str, limit: int | None = None, order: str | None = None, tags: list | None = None, filters: dict | None = None, flag: bool | None = None, either=None, anything=None) -> str:"
            ),
            "{content}"
        );
        assert!(
            content.contains(
                "    \"\"\"Search issues.\n\n    Args:\n        query: JQL query \\\"text\\\".\n        order: One of: asc, desc.\n    \"\"\""
            ),
            "{content}"
        );
        let python = std::env::var("PYTHON").unwrap_or_else(|_| "python3".to_string());
        let output = std::process::Command::new(&python)
            .arg("-c")
            .arg(format!(
                "import sys; sys.path.insert(0, {dir:?}); import typed; print(typed.search_issues.__doc__)",
                dir = dir.path().display().to_string()
            ))
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(String::from_utf8_lossy(&output.stdout).contains("query: JQL query \"text\"."));
    }
}
